<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Services\Admin\AiService;
use Illuminate\Http\Request;

class AiController extends Controller
{
    protected AiService $aiService;

    public function __construct(AiService $aiService)
    {
        $this->aiService = $aiService;
    }

    /**
     * Generate a book description.
     */
    public function generateDescription(Request $request)
    {
        $request->validate([
            'title' => 'required|string|min:3|max:100',
            'category' => 'nullable|string',
        ]);

        $description = $this->aiService->generateDescription(
            $request->title,
            $request->category ?? ''
        );

        return response()->json(['description' => $description]);
    }


    /**
     * Bulk create books with AI.
     */
    public function bulkCreate(Request $request)
    {
        $request->validate([
            'category_id' => 'required|exists:categories,id',
            'language' => 'required|string|max:50',
            'count' => 'required|integer|min:1|max:10',
            'topic' => 'nullable|string|max:100',
            'stock' => 'nullable|integer|min:0',
        ]);

        $category = \App\Models\Category::find($request->category_id);
        
        // Find or create a default "AI Generated" author
        $defaultAuthor = \App\Models\Author::firstOrCreate(
            ['name' => 'AI Generated'],
            ['bio' => 'Books generated by artificial intelligence', 'image' => 'default.png', 'status' => 'active']
        );

        // Get some real authors for variety
        $realAuthors = \App\Models\Author::where('status', 'active')
            ->where('name', '!=', 'AI Generated')
            ->inRandomOrder()
            ->limit(3)
            ->get();

        $books = $this->aiService->generateBooks(
            $category->name,
            $request->language,
            (int) $request->count,
            $request->topic ?? ''
        );

        $created = 0;
        foreach ($books as $bookData) {
            if (empty($bookData['title'])) continue;

            $book = \App\Models\Book::create([
                'category_id' => $category->id,
                'title' => $bookData['title'],
                'slug' => \Illuminate\Support\Str::slug($bookData['title']) . '-' . uniqid(),
                'isbn' => 'AI-' . strtoupper(uniqid()),
                'price' => $bookData['price'] ?? 25000,
                'stock_quantity' => $request->stock ?? rand(10, 100),
                'language' => $request->language,
                'published_date' => now()->subDays(rand(30, 365)),
                'description' => $bookData['description'] ?? '',
                'image' => 'default.png',
                'status' => 'active',
                'created_by' => auth('staff')->id(),
                'updated_by' => auth('staff')->id(),
            ]);

            // Assign a random real author (70%) or AI Generated (30%)
            if ($realAuthors->isNotEmpty() && rand(1, 100) <= 70) {
                $book->authors()->attach($realAuthors->random()->id);
            } else {
                $book->authors()->attach($defaultAuthor->id);
            }

            // Also assign the "AI Generated" author as co-author
            if (rand(1, 100) <= 50) {
                $book->authors()->attach($defaultAuthor->id);
            }

            $created++;
        }

        return response()->json([
            'message' => "{$created} books created successfully with authors!",
            'count' => $created,
        ]);
    }

    /**
     * Generate a promotion message.
     */
    public function generatePromotion(Request $request)
    {
        $request->validate([
            'subject' => 'required|string|min:5|max:200',
            'audience' => 'nullable|string',
        ]);

        $message = $this->aiService->generatePromotionMessage(
            $request->subject,
            $request->audience ?? 'all'
        );

        return response()->json(['message' => $message]);
    }

}
